<a href="https://colab.research.google.com/github/c7934597/Python_Basic_Practice/blob/master/NumPyCh1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

'''
建立一個陣列，並給予一些初始值！
這邊分別以兩種型別(整數、浮點數)的數值來做範例，整數、浮點數分別為a和b。
ndarray.dtype：該陣列型別的屬性
'''

a = np.array([1, 2, 3, 4, 5])
print("a=>{0}".format(a))
print("a.dtype=>{0}".format(a.dtype))
print()
b = np.array([1.25, 2.25, 3.25, 4.25, 5.25])
print("b.dtype=>{0}".format(b.dtype))

a=>[1 2 3 4 5]
a.dtype=>int64

b.dtype=>float64


In [0]:
'''
重要屬性
ndarray.ndim：NumPy ndarray物件的維度
ndarry.shape：ndarry物件的每一個維度的大小(size)，回傳資料類別為Tuple
ndarry.size：ndarry物件所組成之array的總元素數量，回應之數值會等於ndarray.shape的每個元素相乘
ndarry.dtype：ndarray物件內組成元素的型態
ndarray.itemsize：陣列中每一個元素的大小(Bytes) (ex: int16=>16/8=2 Bytes)
ndarry.data：這是一個存有實際陣列元素的緩衝，通常我們不需要使用這個屬性，因為我們可以使用index存取這些元素。

'''

aa = np.array([(1.9, 1.5, 1.3), (2.9, 2.5, 2.3),(6.9, 8.5, 8.3)], dtype=np.int16)
# ndarray.ndim
print("ndim:{0}".format(aa.ndim))
# ndarry.shape
print("shape:{0}".format(aa.shape))
# ndarry.size
print("size:{0}".format(aa.size))
# ndarry.dtype
print("dtype:{0}".format(aa.dtype))
# ndarray.itemsize
print("itemsize:{0}".format(aa.itemsize))
# ndarry.data
print("data:{0}".format(aa.data))

ndim:2
shape:(3, 3)
size:9
dtype:int16
itemsize:2
data:<memory at 0x7f6d146ae048>


In [0]:
'''
建立陣列的方法
1維陣列
np.array( [<陣列元素用逗號隔開>] )：簡易一維陣列
np.arange( 起始值, 結束值, 步幅, 資料型別 )：也是產生一維陣列，和np.array()的差別在於arange擁有較大的彈性，而且元素數值是自動化產生！
'''

## 1維陣列
a = np.array([6, 5, 4, 3, 2])
print("a=>{0}".format(a))
print()
b = np.arange(10)
print("b=>{0}".format(b))
print()
c = np.arange(0, 10, 1.5, dtype=np.float64)
print("c=>{0}".format(c))

a=>[6 5 4 3 2]

b=>[0 1 2 3 4 5 6 7 8 9]

c=>[0.  1.5 3.  4.5 6.  7.5 9. ]


In [0]:
'''
2維陣列
np.array( [[<Row1陣列元素>], [<Row2陣列元素>]] )：產生簡易二維陣列
'''

## 2維陣列 2-by-3 array
b = np.array([[1.1, 1.2, 1.3], [2.1, 2.2, 2.3]])
print("b=>{0}".format(b))

b=>[[1.1 1.2 1.3]
 [2.1 2.2 2.3]]


In [0]:
'''
指定陣列型別
np.array( [[<Row1陣列元素>], [<Row2陣列元素>]], dtype=np.int16 )：產生型別為int的陣列
'''

## Assign a particular data type to an array
aa = np.array([[1.9, 1.5, 1.3], [2.9, 2.5, 2.3]], dtype=np.int16)
print("aa=>{0}".format(aa))

aa=>[[1 1 1]
 [2 2 2]]


In [0]:
'''
複數陣列(Complex)
很簡單，就是把陣列元素用複數表示法指定就好了：實部+虛部j
或者是用dtype=complex指定陣列元素為複數！
'''

c1 = np.array([(1.1, 1.2, 1.3), (2.1, 2.2, 2.3)], dtype=complex)
print("c1=>{0}".format(c1))
print()
c2 = np.array([2.1+6j, 3.2+9j, 4.3+12j])
print("c2=>{0}".format(c2))

c1=>[[1.1+0.j 1.2+0.j 1.3+0.j]
 [2.1+0.j 2.2+0.j 2.3+0.j]]

c2=>[2.1 +6.j 3.2 +9.j 4.3+12.j]


In [0]:
'''
建立陣列常用函數
Zeros
np.zeros( (陣列各維度大小用逗號區分) )：建立全為0的陣列，可以小括號定義陣列的各個維度的大小！
'''

zeros = np.zeros( (3, 5) )
print("zeros=>{0}".format(zeros))

zeros=>[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [0]:
'''
Ones
np.ones( (陣列各維度大小用逗號區分) )：用法與np.zeros一樣！
'''

## Ones
ones = np.ones( (3, 5) )
print("ones=>{0}".format(ones))

ones=>[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [0]:
'''
Empty
np.empty( (陣列各維度大小用逗號區分) )：用法與np.zeros一樣，但唯一的差別是NumPy不會初始化陣列內元素的初始值，所以內容將會是不確定的。
'''

## Empty
## It means that we want to declare a uninitialized matrix.
e = np.empty( (2, 5) )
print("e=>{0}".format(e))

e=>[[0.0e+000 4.9e-324 9.9e-324 1.5e-323 2.0e-323]
 [2.5e-323 3.0e-323 3.5e-323 4.0e-323 4.4e-323]]


In [0]:
'''
Arange
np.arange( 起始值, 結束值, 步幅, 資料型別 )：也是產生一維陣列，
和np.array()的差別在於arange擁有較大的彈性，而且元素數值是自動化產生！步幅決定每隔多少數值產生一個元素(等差的概念)。
'''

## Arange
r1 = np.arange(25, 30, .5)
print("r1=>{0}".format(r1))

r1=>[25.  25.5 26.  26.5 27.  27.5 28.  28.5 29.  29.5]


In [0]:
'''
Linspace
np.linspace( 起始值, 結束值, 起始與結束的區間內要產生幾個元素 )：這個在畫線時還蠻常用到的！
只要給定陣列的區間(起始值、結束值)，就可以要求在這個區間內產生幾個元素！
'''

## Linspace
lin = np.linspace(3, 5, 9)
print("lin=>\n{0}".format(lin))

lin=>
[3.   3.25 3.5  3.75 4.   4.25 4.5  4.75 5.  ]
