<a href="https://colab.research.google.com/github/c7934597/Python_Basic_Practice/blob/master/NumpyCh3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
'''
加、減、次方
基礎運算-1
加、減、次方的計算非常直覺好懂，分別使用『 + 、 – 、 ** 』就可以了。
例如：加、減、次方都可以直接做單一數值的同加、同減、次方。
'''

import numpy as np

print('維度相同的矩陣相加、減:')
# 維度相同的矩陣相加、減
a = np.array( [6, 7, 8, 9] )
b = np.arange( 4 )
c = a - b
print("a=>{0}".format(a))
print("b=>{0}".format(b))
print("c=>{0}".format(c))
 
 
print('\n同加、同減一個數值:')
# 同加、同減一個數值
a += 5
print("a=>{0}".format(a))
b -= 5
print("b=>{0}".format(b))
 
 
print('\n次方：')
# d是b的2次方
# d is squared of b.
d = b**2
print("d=>{0}".format(d))

維度相同的矩陣相加、減:
a=>[6 7 8 9]
b=>[0 1 2 3]
c=>[6 6 6 6]

同加、同減一個數值:
a=>[11 12 13 14]
b=>[-5 -4 -3 -2]

次方：
d=>[25 16  9  4]


In [0]:
'''
同除、同乘特定數
基礎運算-2
矩陣(matrix)同乘上某個特定純量(scalar)也很簡單，就直接相乘就好了！
'''

a = np.arange(5)
b = np.arange(10, 5, -1)
print("a=>{0}".format(a))
print("b=>{0}".format(b))
print("\n同除:")
# c等於a同除以2
c = a / 2
print("c=>{0}".format(c))

print("\n轉整數:")
print(c.astype(int))
 
print("\n同乘:")
# d等於b同乘以2
d = b * 2
print("d=>{0}".format(b))

a=>[0 1 2 3 4]
b=>[10  9  8  7  6]

同除:
c=>[0.  0.5 1.  1.5 2. ]

轉整數:
[0 0 1 1 2]

同乘:
d=>[10  9  8  7  6]


In [0]:
# 矩陣相乘
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
print("A, B相乘(矩陣乘法) =>\n{0}".format(A.dot(B)))
print()
print("A, B相對應位置相乘=>\n{0}".format(A*B))

A, B相乘(矩陣乘法) =>
[[19 22]
 [43 50]]

A, B相對應位置相乘=>
[[ 5 12]
 [21 32]]


In [0]:
'''
取代
取代
這個也很常用到喔，像是有時候要把矩陣裡面NaN的數值取代成0的時候就很好用！
舉例：判斷陣列元素值小於等於0的元素，把那些元素的數值取代成1
'''

# 印出陣列中小於等於0的元素
e = np.array([5, -1, 3, 9, 0])
print("陣列e裡面哪幾個位置的元素值小於等於零?:{0}".format(e<=0))
 
# 把小於等於0的元素取代成1
e[e<=0] = 1
print("把小於等於0的元素取代成1=>{0}".format(e))

陣列e裡面哪幾個位置的元素值小於等於零?:[False  True False False  True]
把小於等於0的元素取代成1=>[5 1 3 9 1]


In [0]:
'''
陣列元素的型別
常犯錯誤
因為NumPy太好用了，導致有時候甚至會忽略兩個要做運算的陣列型別根本不符，最後就會出錯～哈
用下列例子給大家了解這種狀況：
'''

## Operations: += *=
a = np.ones((2, 3), dtype=np.float)
b = np.random.random((2,3))

a *= 5
print("a=>\n{0}".format(a))
b += a
print("b=>\n{0}".format(b))
 
a += b
print("a=>\n{0}".format(a))


a=>
[[5. 5. 5.]
 [5. 5. 5.]]
b=>
[[5.55757803 5.39473183 5.57315757]
 [5.17041489 5.22084062 5.8650287 ]]
a=>
[[10.55757803 10.39473183 10.57315757]
 [10.17041489 10.22084062 10.8650287 ]]


In [0]:
'''
如果把上面範例第二行程式的 np.float 改成 np.int 就會出錯喔！
下列程式第11行：硬是用型別為int的矩陣加上一個型別為float的矩陣，肯定會出錯的吧！
'''

## Operations: += *=
a = np.ones((2, 3), dtype=np.int)
b = np.random.random( (2,3) )
a *= 5
print("a=>\n{0}".format(a))
b += a
# float64 = float64 + int64
print("b=>\n{0}".format(b))
 
# int64 = int64 + float64
a += b
print("a=>\n{0}".format(a))

a=>
[[5 5 5]
 [5 5 5]]
b=>
[[5.76089549 5.66127998 5.46144284]
 [5.47066847 5.76082421 5.74131106]]


TypeError: ignored

In [0]:
'''
矩陣的屬性
常用方法-1
NumPy矩陣本身在初始化之後就內建一些好用的方法！
sum：矩陣加總
min：矩陣最小值
max：矩陣最大值
mean：矩陣平均值
'''

## Methods: sum, min, max, mean
a = np.random.random((3, 3))
print("sum=>{0}\nmax=>{1}\nmin=>{2}\nmean=>{3}".format(a.sum(), a.max(), a.min(), a.mean()))
1
2
3
## Methods: sum, min, max, mean
a = np.random.random((3, 3))
print("sum=>{0}\nmax=>{1}\nmin=>{2}\nmean=>{3}".format(a.sum(), a.max(), a.min(), a.mean()))

sum=>5.106440298852572
max=>0.9313489271125839
min=>0.02197584623034954
mean=>0.5673822554280635
sum=>3.310586567315604
max=>0.9919592141061149
min=>0.054119444175696696
mean=>0.367842951923956


In [0]:
'''
矩陣的一些方法
常用方法-2
sum：axis=0或1  算是進階用法，可以指定要加總的維度是哪一個
cumsum：這是可以拿來對陣列值做出累計加總的效果，可以用在一維陣列上，數值就可以直接拿來畫出累計趨勢圖喔～
'''

b = np.arange(12).reshape(2, 6)
print("b=>\n{0}".format(b))
 
print()
# 加總每一欄(column)
print("b.sum(axis=0)=>{0}".format(b.sum(axis=0)))
 
print()
# 加總每一列(row)
print("b.sum(axis=1)=>{0}".format(b.sum(axis=1)))
 
print()
revenu = np.round(np.random.random((1,12)) * 100, 0) # np.round  四捨五入到指定小數位
revenu = revenu.astype(int)
print("revenu=>\n{0}".format(revenu))
 
print()
# 累計加總(每一項數值等於自己加上前一項)
print("Cumulative Sum of revenu=>\n{0}".format(revenu.cumsum()))

b=>
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]

b.sum(axis=0)=>[ 6  8 10 12 14 16]

b.sum(axis=1)=>[15 51]

revenu=>
[[33 98  7 90 26 47 25 74 83 11 44 23]]

Cumulative Sum of revenu=>
[ 33 131 138 228 254 301 326 400 483 494 538 561]


In [0]:
'''
常用方法-3
np.sqrt：矩陣內所有元素開平方根
np.exp：矩陣內所有元素進行Exponential function(e)運算
np.add：矩陣或陣列相加
'''

B = np.arange(3)
B_exp = np.exp(B)
print("B_exp=> {0}".format(B_exp))
 
B_sqrt = np.sqrt(B)
print("B_sqrt=> {0}".format(B_sqrt))
 
C = np.array([2, 1, 0])
print("np.add(B, C)=> {0}".format(np.add(B, C)))

B_exp=> [1.         2.71828183 7.3890561 ]
B_sqrt=> [0.         1.         1.41421356]
np.add(B, C)=> [2 2 2]


In [0]:
'''
np.add：矩陣或陣列相加
'''

x1 = np.arange(9).reshape((3, 3))
print("{0}\n".format(x1))
x2 = np.arange(3)
print("{0}\n".format(x2))
np.add(x1, x2)

[[0 1 2]
 [3 4 5]
 [6 7 8]]

[0 1 2]



array([[ 0,  2,  4],
       [ 3,  5,  7],
       [ 6,  8, 10]])